export const GET_CONTACT_LIST = 'GET_CONTACT_LIST';
export const GET_CONTACT_LIST_LOADING = 'GET_CONTACT_LIST_LOADING';
export const GET_CONTACT_LIST_SUCCESS = 'GET_CONTACT_LIST_SUCCESS';
export const GET_CONTACT_LIST_ERROR = 'GET_CONTACT_LIST_ERROR';

export const ADD_CONTACT = 'ADD_CONTACT';
export const GET_CONTACT = 'GET_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SEARCH_CONTACT = 'SEARCH_CONTACT';
export const CLEAR_CURRENT_CONTACT = 'CLEAR_CURRENT_CONTACT';

export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';
export const SET_HIDE_MODAL = 'SET_HIDE_MODAL';
